-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    username character varying(64) COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    avatar_url text COLLATE pg_catalog."default",
    is_premium boolean NOT NULL DEFAULT false,
    country_code character varying(2) COLLATE pg_catalog."default",
    is_active boolean NOT NULL DEFAULT true,
    theme_config jsonb NOT NULL DEFAULT jsonb_build_object('primary', '#6366f1', 'accent', '#8b5cf6', 'bg', '#0a0a0f', 'preset', 'dark'),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_sessions
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    device_info text COLLATE pg_catalog."default" NOT NULL DEFAULT 'unknown'::text,
    refresh_token text COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    last_used_at timestamp with time zone NOT NULL DEFAULT now(),
    revoked boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_sessions_pkey PRIMARY KEY (id, user_id)
);

CREATE TABLE IF NOT EXISTS public.tracks
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    album_id uuid,
    artist_id uuid,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    artist character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Unknown artist'::character varying,
    album character varying(255) COLLATE pg_catalog."default",
    year integer,
    genre character varying(120) COLLATE pg_catalog."default",
    duration_ms integer,
    track_number integer,
    is_explicit boolean NOT NULL DEFAULT false,
    play_count integer NOT NULL DEFAULT 0,
    path text COLLATE pg_catalog."default" NOT NULL,
    cover_path text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    embedding vector(1536),
    search_vector tsvector,
    CONSTRAINT tracks_pkey PRIMARY KEY (id, album_id, artist_id),
    CONSTRAINT tracks_path_key UNIQUE (path)
);

CREATE TABLE IF NOT EXISTS public.playlists
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    owner_id uuid NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    search_vector tsvector,
    CONSTRAINT playlists_pkey PRIMARY KEY (id, owner_id)
);

CREATE TABLE IF NOT EXISTS public.playlist_tracks
(
    playlist_id uuid NOT NULL,
    track_id uuid NOT NULL,
    added_by uuid,
    added_at timestamp with time zone NOT NULL DEFAULT now(),
    "position" integer,
    CONSTRAINT playlist_tracks_pkey PRIMARY KEY (playlist_id, track_id)
);

CREATE TABLE IF NOT EXISTS public.playlist_invites
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    playlist_id uuid NOT NULL,
    created_by uuid NOT NULL,
    token text COLLATE pg_catalog."default" NOT NULL,
    role text COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT playlist_invites_pkey PRIMARY KEY (id, playlist_id),
    CONSTRAINT playlist_invites_token_key UNIQUE (token)
);

CREATE TABLE IF NOT EXISTS public.playlist_collaborators
(
    playlist_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT playlist_collaborators_pkey PRIMARY KEY (playlist_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.listening_events
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid,
    track_id uuid NOT NULL,
    artist_id uuid,
    source text COLLATE pg_catalog."default",
    country_code character varying(8) COLLATE pg_catalog."default",
    city text COLLATE pg_catalog."default",
    played_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT listening_events_pkey PRIMARY KEY (id, user_id, track_id, artist_id)
);

CREATE TABLE IF NOT EXISTS public.favorites
(
    user_id uuid NOT NULL,
    track_id uuid NOT NULL,
    added_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT favorites_pk PRIMARY KEY (user_id, track_id)
);

CREATE TABLE IF NOT EXISTS public.artists
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    search_vector tsvector,
    CONSTRAINT artists_pkey PRIMARY KEY (id),
    CONSTRAINT artists_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.albums
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    artist character varying(255) COLLATE pg_catalog."default",
    year integer,
    cover_path text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT albums_pkey PRIMARY KEY (id)
);
END;